name: Build and Publish to Docker and Nuget
on:
  workflow_dispatch:
    inputs:
      publish_nuget:
        type: boolean
        default: false
        description: 'Publish NuGet package?'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Mcp.Dataverse.Stdio

    - name: Build project
      run: dotnet build ./src/Mcp.Dataverse.Stdio --configuration Release

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Docker Hub
      run: dotnet publish ./src/Mcp.Dataverse.Stdio -c Release /t:PublishContainer --verbosity detailed
      env:
        DOCKER_REGISTRY: docker.io

    - name: Build and pack NuGet package
      run: dotnet pack ./src/Mcp.Dataverse.Stdio -c Release -o ./nupkgs

    - name: Publish NuGet package
      if: github.event.inputs.publish_nuget == 'true'
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json